### ISSUE TITLE
Crash while reading the configuration file.

### ISSUE THREAD

**Issue by Fenixin** [lolouk44/hassio-addons#16]
Hello again! Just updated to the last version.

**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Describe the bug**
Xiaomi Mi Scale crashes while reading the config file with this error:
```
-------------------------------------
2020-09-09 09:42:40 - Starting Xiaomi mi Scale...
2020-09-09 09:42:40 - Loading Config From Add-On Options...
2020-09-09 09:42:40 - Config Loaded...
Traceback (most recent call last):
  File "/opt/miscale/Xiaomi_Scale.py", line 344, in <module>
    main()
  File "/opt/miscale/Xiaomi_Scale.py", line 312, in main
    if MQTT_DISCOVERY.lower() in ['true', '1', 'y', 'yes']:
AttributeError: 'bool' object has no attribute 'lower'
```

**To Reproduce**
Update to the last version and try to start the add-on.

**Expected behaviour**
I would expect it to load the configuration file without crashing. Also, seeing that you are treating the MQTT_DISCOVERY paramater as string I tried to put that parameter in the config file between quotation marks, but didn't help. It was like this:
```
MQTT_DISCOVERY: true
```
And tried like this:
```
MQTT_DISCOVERY: 'true'
```
None of them worked

**Scale (please complete the following information):**
 - Name Mi Body Composition Scale
 - Model XMTZC02HM

**Device running Home Assistant (please complete the following information):**
 - Raspberry pi 4 B 4GB
 - Built-in

**Comment by fufar** [comment]
same error on 0.1.9

**Comment by lolouk44** [comment]
Thanks both, I've located the issue and fixed it
Currently pushing 0.1.10...

**Comment by lolouk44** [comment]
fixed in 0.1.10

**Comment by fufar** [comment]
after 0.1.10 this error gone, but something still broken - cant see weight in lovelace

in log
`-------------------------------------
2020-09-09 22:59:30 - Starting Xiaomi mi Scale...
2020-09-09 22:59:30 - Loading Config From Add-On Options...
2020-09-09 22:59:30 - Config Loaded...
2020-09-09 22:59:30 - Discovery Completed...
2020-09-09 23:00:06 - Measuring Unit: 82
2020-09-09 23:00:06 - Measured Raw Weight: 0.6
2020-09-09 23:00:41 - Measuring Unit: 82
2020-09-09 23:00:41 - Measured Raw Weight: 0.6
2020-09-09 23:01:16 - Measuring Unit: 82
2020-09-09 23:01:16 - Measured Raw Weight: 0.6
2020-09-09 23:01:51 - Measuring Unit: 82
2020-09-09 23:01:51 - Measured Raw Weight: 0.6`

in entity

![image](https://user-images.githubusercontent.com/22238388/92647575-c3d7e400-f2f0-11ea-95ca-2b90bf917ed8.png)

in lovelace

![image](https://user-images.githubusercontent.com/22238388/92647615-d5b98700-f2f0-11ea-9bbe-bd0ba245aec1.png)

**Comment by lolouk44** [comment]
There was a breaking change in 0.1.8
All json attributes are now in lower snake_case
You need to adjust your HA config and replace `Weight` with `weight`
